version: 2

jobs:
  build:
    docker:
      - image: circleci/node:7.9.0

    working_directory: ~/electron-bomb

    steps:
      - checkout

      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn install
      - run: yarn lint

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
